### PR TITLE
Light refactorings

### PR DESCRIPTION
**Pull request by adamnemecek**

### CODE REVIEW

**Comment by orta** [comment]
This is quite a lot of code to just drop without any description, can you please write up a summary of your changes and why?

**Comment by adamnemecek** [comment]
It's all refactoring of the current code? Why? I believe that my refactorings increase clarity or reduce source code size.

**Comment by orta** [comment]
It currently exists in a vacuum, I'm not really done any Swift in a year, and have never used this library -yet I am the maintainer. I would struggle to judge whether to merge and take over your changes without some kind of explanation?

**Comment by orta** [comment]
Thanks for the PR - given the number of of conflicted files and lack of response in a while - I'm going to close this 👍

**Pull request closed without merging**
