### PR TITLE
Xcode 10.2 / Swift 5

### PR DESCRIPTION
**Pull request by jwietelmann**
This is just @netizen01's PR with an `osx_image` version bump for Travis.

### CODE REVIEW

**Comment by kajensen** [comment]
Looks like this podspec is expecting the 1.7 cocoapods beta?

```
Analyzing dependencies
Pre-downloading: `Cartography` from `https://github.com/jwietelmann/Cartography.git`, branch `master`
[!] Failed to load 'Cartography' podspec: 
[!] Invalid `Cartography.podspec` file: undefined method `swift_versions=' for #<Pod::Specification name="Cartography">
Did you mean?  swift_version=
               swift_version.

 #  from /var/folders/h_/mq1fjrjj0cb70mhnxzg6by3c0000gn/T/d20190422-33286-b5wrcb/Cartography.podspec:15
 #  -------------------------------------------
 #  
 >    s.swift_versions = ["4.2","5.0"]
 #  
 #  -------------------------------------------

```

**Comment by jwietelmann** [comment]
@kajensen Sorry, I don't know anything about that. I literally just forked someone else's fork and updated the Travis yaml so that CI would pass.

**Comment by kajensen** [comment]
Sorry, I should've commented this on @netizen01 pull request #308

**Comment by jwietelmann** [comment]
@kajensen see if this fixes it for you. i cavalierly just edited it straight in github and didn't test. (i'm in the middle of doing my day job.)

**Comment by kajensen** [comment]
Yep thats the fix! This should be approved over #308

**Comment by typfel** [comment]
What's preventing this from being merged?

**Comment by orta** [comment]
Nothing really, it wasn't green when I last looked 👍 

Let's do it

**Pull request merged**
