### PR TITLE
Add Safe Area Layout support

### PR DESCRIPTION
**Pull request by yysskk**
iOS11 added the concept of [Safe Area](https://developer.apple.com/documentation/uikit/uiview/positioning_content_relative_to_the_safe_area). It would be nice to be able to use it. I supported to it using safeAreaLayoutGuide, but how about you?

### CODE REVIEW

**Comment by orta** [comment]
This looks great - as this is a library used by a lot of people and we don't want to break features in the future, can you add some tests to cover your changes 👍

**Comment by yysskk** [comment]
@orta Thanks, review! I am glad to accept you. I added tests, so please take a look.

**Comment by orta** [comment]
These tests are 💯 - amazing

**Comment by orta** [comment]
Shipped as 2.1.0 

screen shot 2017-10-17 at 9 35 16 pm

**Comment by mathieutozer** [comment]
Did this change get reverted? I don't see it in the latest release via Cocoapods!

**Comment by inamiy** [comment]
API changed in https://github.com/robb/Cartography/pull/269 for ver 3.x.

**Comment by Curerer** [comment]
truongdinh76542@gmail.com

**Pull request merged**
