### PR TITLE
Add support for update existing constraint from `install()`.

### PR DESCRIPTION
**Pull request by devxoul**
Concept
-------

### 1. Update constant

If the new constraint is exactly the same with existing, `layout()` will just update a constant of existing constraint.

```swift
layout(view) { view in
    view.top == view.superview!.top + 10
    view.left == view.superview!.left + 10
    view.width == 200
}

// just update constants
layout(view) { view in
    view.top == view.superview!.top + 20
    view.width == 300
}
```

### 2. Replace existing constraint

If the new constraint has different relation from existing, `layout()` will uninstall existing and install the new one.

```swift
layout(view) { view in
    view.left == someView.top.left + 10
}

// replace existing constraint with new one
layout(view) { view in
    view.left == anotherView.top.left + 50
}
```

Animations
----------

~~Cartography doesn't support animations currently. Because Cartography immediately layout subviews after constraints are installed.~~

Use `constrain()` instead of `layout()` for animations, as @robb mentioned. What we need to do is to call `layoutIfNeeded()` in animation block.

For example:

```swift
// use `constrain()` instead of `layout()`
constrain(view) { view in
    view.left == view.superview!.left + 200
}

// layout in animation block
UIView.animateWithDuration(0.5, animations: {
    view.layoutIfNeeded()
})
```

Or you can pass `view.layoutIfNeeded` to an animation block:

```swift
UIView.animateWithDuration(0.5, animations: view.layoutIfNeeded)
```

I'll make a PR for this as soon as possible.

Related Issues
--------------

- Replace Existing Constraint #26

### CODE REVIEW

**Comment by robb** [comment]
Thanks for the pull request :sparkling_heart: 

However, I've looked into this [before](https://github.com/robb/Cartography/commit/65773e0340dce16bae288062d363d2bbcd7dd558) but I considered the implicit replacement of constraints to yield to many edge cases. Consider this spec:

```Swift
import Cartography
import XCTest

class UpdateTests2: XCTestCase {
    var superview: View!
    var view1: View!
    var view2: View!

    override func setUp() {
        superview = View(frame: CGRectMake(0, 0, 400, 400))

        view1 = View(frame: CGRectZero)
        superview.addSubview(view1)

        view2 = View(frame: CGRectZero)
        superview.addSubview(view2)
    }

    func testUpdate() {
        layout(view2) { view2 in
            view2.height == 300
            view2.width  == 300
        }

        layout(view1, view2) { view1, view2 in
            view1.center == view2.center

            view1.width  == view2.width
            view1.height == view2.height
        }

        layout(view1) { view1 in
            // This should replace `view1.height == view2.height`
            view1.width  == 200; return
        }

        XCTAssert(CGRectGetWidth(view1.frame) == 200, "It should update existing constraint")
    }
}
```

You would expect `view1.width  == 200;` to replace the earlier `view1.height == view2.height` constraint, but since that one is attached to `view1.superview`, we get unsatisfiable constraints – a symbolic breakpoint in `UIViewAlertForUnsatisfiableConstraints` confirms this.

(Note that the spec may actually pass if UIKit decides to break the right constraint. For me it breaks `view2.width  == 300` which is definitely not what I wanted)

> Because Cartography immediately layout subviews after constraints are installed.

Have you tried the new (and undocumented :pensive:) [`contrain`](https://github.com/robb/Cartography/blob/fbfe8bce75d905a466aca1cde72091cd057bbf06/Cartography/Layout.swift#L52-L91) function?

You should be able to do something like 

```swift
// this won't call `setNeedsLayout()`
constrain(view) { view in
    view.left == view.superview!.left + 200
}

// layout in animation block
UIView.animateWithDuration(0.5, animations: view.layoutIfNeeded)
```

**Comment by devxoul** [comment]
@robb 

Oh, that isn't what I want to do. What I wanted to make `layout` function to do was 'Create new constraints or update existing'. Not replace whole constraints.

For example:

```swift
layout(view1, view2) { (view1, view2) in
    view1.top == view2.top + 10
    view2.left == view2.left + 10
}
// at this time:
// view1.top = view2.top + 10
// view2.left = view2.left + 10

layout(view1, view2, anotherView) { (view1, view2, anotherView) in
    view1.top == anotherView.bottom + 20 // update
    view1.height = view2.height - 10 // create new one
}
// then:
// view1.top = anotherView.bottom + 20 (replaced)
// view1.legt = view2.left + 10 (existing, not changed)
// view1.height = view2.height - 10 (newely created)
```

I've just tried `constrain` function, it works perfectly as I expected :D

**Comment by robb** [comment]
> What I wanted to make layout function to do was 'Create new constraints or update existing'. Not replace whole constraints.

Hmm, not sure I follow. Let's stick with `width` and `height` since those actually allow referencing constants, where I think most of the confusion comes into play. Consider this example:

```swift
layout(view1, view2) { (view1, view2) in
    view1.width  == view2.width  - 10
    view1.height == view2.height - 10
}

layout(view1, view2, anotherView) { (view1, view2, anotherView) in
    view1.width  == anotherView.width + 20
    view1.height == view2.height - 20
}
```

Assuming `view1`, `view2` and `anotherView` and all share the same common superview, this works as expected.

However, just from looking at it, I would expect this to work as well:

```swift
layout(view1, view2) { (view1, view2) in
    view1.width  == view2.width  - 10
    view1.height == view2.height - 10
}

layout(view1, view2) { (view1, view2) in
    view1.width  == 100
    view1.height == view2.height - 20
}
```

which doesn't because of the aforementioned reasons.

> I've just tried constrain function, it works perfectly as I expected :D

:ok_hand:

**Comment by devxoul** [comment]
@robb, you're right. I didn't catch that :astonished:

Then, how about 'create new constraint or update **constant** of existing'?

**Comment by robb** [comment]
```swift
constrain(view1) { view1 in
    view1.width  == 100
    view1.height == 100
}

constrain(view1) { view1 in
    view1.width  == 200
    view1.height == 200
}
```

and this would work:

```swift
constrain(view1, view2) { view1, view2 in
    view1.width  == view2.width  + 100
    view1.height == view2.height + 100
}

constrain(view1, view2) { view1, view2 in
    view1.width  == view2.width  + 200
    view1.height == view2.height + 200
}
```

but this wouldn't

```swift
constrain(view1) { view1 in
    view1.width  == 100
    view1.height == 100
}

constrain(view1) { view1 in
    view1.width  == view2.width  + 200
    view1.height == view2.height + 200
}
```

Then there's stuff like:

```swift
let leftColumnHeight: Double = // …

constrain(marginView) { marginView in
    marginView.height >= leftColumnHeight
}


let rightColumnHeight: Double = // …

constrain(marginView) { marginView in
    marginView.height >= rightColumnHeight
}
```

Would this update the `height` constraint or create a second one? I have no clue….

I think a better way to update constraints is capturing them, e.g.:

```swift
var width: NSLayoutConstraint? = nil

constrain(view1) { view1 in
    width = view1.width == 100
}

// Later

width.constant == 200
```

which can get unwieldy but it overall simpler, imho.

**Comment by devxoul** [comment]
Totally agree with that, but how about this approaches?

1) Capture referencing views:

```swift
// block A (init block)
constrain(view1) { view1 in
    view1.width  == view2.width  + 200
    view1.height == view2.height + 200
}

// block B (update block)
constrain(view1) { view1 in
    view1.width  == 100
    view1.height == 100
}
```

At **block A**, constraints installed on `view1.superview`. We can capture `view1.superview` from `view1` at install time, so at **block B**, we can use captured view to find existing constraints. I just wrote some prototype and it works.

2) Update layout explicitly:

```swift
let leftColumnHeight: Double = // …

// force create
layout(marginView) { marginView in
   marginView.height >= leftColumnHeight
}


let rightColumnHeight: Double = // …

// force update
updateLayout(marginView) { marginView in
   marginView.height >= rightColumnHeight
}
```

Capturing each constraints is the most simple way to update constants, but it's too messy if there are many UI elements and various exceptional cases.

**Pull request closed without merging**
