### PR TITLE
Remove layout functions

### LINKED ISSUE #143: Should `layout` be removed?
Seems like `constrain` with a manual `view.layoutIfNeeded` is a better practice and would allow reducing the API surface quite a bit.

### PR DESCRIPTION
**Pull request by robb**
Fixes #143

### CODE REVIEW

**Comment by robb** [comment]
@smileyborg what's your opinion on this?

**Comment by smileyborg** [comment]
I agree with #143 for sure, is that what you're asking? There are a bunch of changes in this PR though so I didn't look them over closely, did you want me to look at anything in particular?

BTW, on the note of significant breaking changes like this, I'd love to also explore what Cartography would look like if it didn't use closures passed to `constraint` (or `layout`) and instead added some "NSLayoutAnchor-like" properties of type `LayoutProxy` to UIView/NSView, which would let you use the custom operators to create constraints without having to pass the view(s) into a closure first. Not sure if you've thought about this at all -- I haven't had time to fully think it through, but it seems like it could be a huge improvement.

**Comment by robb** [comment]
> I agree with #143 for sure, is that what you're asking? 

Yeah, basically. No need to review this, I'm confident enough in the diff ;-)

**Comment by robb** [comment]
Oh, and thanks :sparkling_heart: dug

**Comment by robb** [comment]
Closed in favor of #146 which targets `1.0-development`.

**Pull request closed without merging**
