### PR TITLE
Array support to `distribute` and `align` methods

### PR DESCRIPTION
**Pull request by corujautx**
I added overloads to both `distribute` and `align` methods in order to support arrays of `LayoutProxy` so we can handle views to align dynamically instead of having to declare each one as mentioned in issues #155 and #193, and set up default values to `distribute` to quickly place views with zero spacing between them.

I also added these changes for those who want to use with Swift 2.3 in a [branch](https://github.com/corujautx/Cartography/tree/swift2.3) within my fork.

### CODE REVIEW

**Comment by orta** [comment]
Do you know if these are covered by existing tests? OR should I be bugging you to add some? :D

**Comment by vitor-travain-movile** [comment]
I added a couple of tests for each method to test when there is a single `LayoutProxy` instance or no instance for both `align` and `distribute` methods, both cases when it is expected to return no constraint at all.

**Comment by corujautx** [comment]
I added four more tests, all of them covering the cases in which no constraint should be returned when the array contains a single or no instance of `LayoutProxy`.

**Comment by orta** [comment]
Awesome 👍

**Comment by ninjudd** [comment]
Is there a release on CocoaPods with this update?

**Comment by orta** [comment]
yep, just shipped in 1.1.0 now

**Pull request merged**
