### PR TITLE
resolve "ld: warning: linking against dylib not safe for use in applicat...

### PR DESCRIPTION
**Pull request by mono0926**
resolve "ld: warning: linking against dylib not safe for use in application extensions" when setting as AppExtensions' target.

### CODE REVIEW

**Comment by robb** [comment]
Thanks for the Pull Request :sparkling_heart: 

Just to make sure I understand this correctly:

When building a framework, setting `APPLICATION_EXTENSION_API_ONLY` assures the linker that no APIs flagged as `NS_EXTENSION_UNAVAILABLE_IOS` are being used?

**Comment by mono0926** [comment]
Thanks, that's right :+1:

**Comment by robb** [comment]
:boom:

**Comment by robb** [comment]
@mono0926 do you need me to tag HEAD?

**Comment by mono0926** [comment]
> do you need me to tag HEAD?

I use my fork for the time being, so don't worry about that.

**Pull request merged**
