### PR TITLE
Make Edge not accept numbers for ==

### LINKED ISSUE #59: `top` et al. should not accept numbers as an argument to `==`
I dont know how to describe this issue: Simply try run this code:

```
import Foundation
import UIKit

public class SettingsViewController: UIViewController {
    
    let signoutButton = UIButton()
    let copyrightTextView = UITextView()
    
    public override func loadView() {
        super.loadView()
        
        signoutButton.setTitle(NSLocalizedString("Odhlásit", comment: ""), forState: .Normal)
        view.addSubview(signoutButton)
        
        copyrightTextView.textAlignment = .Center
        copyrightTextView.editable = false
        copyrightTextView.text = NSLocalizedString("Copyright 2015 Springtide Ventures s.r.o.", comment: "")
        copyrightTextView.scrollEnabled = false
        copyrightTextView.backgroundColor = UIColor.clearColor()
        copyrightTextView.textColor = UIColor.blackColor()
        view.addSubview(copyrightTextView)
        let height = copyrightTextView.sizeThatFits(CGSize(width: view.bounds.width, height: CGFloat.max)).height
        
        constrain(copyrightTextView, signoutButton) { c, l in
            l.centerX == l.superview!.centerX
            l.width == l.superview!.width
            l.top == 100
            
            c.top == l.bottom + 20
            c.centerX == l.centerX
            c.height == Float(height)
        }
        
    }
    
}
```

### PR DESCRIPTION
**Pull request by robb**
Fixes #59

### CODE REVIEW

**Comment by robb** [comment]
Maybe `ConstantEquality` should be `NumericalEquality` instead? Could a native speaker chime in on this? :gb: :us: :

**Comment by robb** [comment]
Paging @orta, speaker of ye olde tongue and giver of names.

**Comment by orta** [comment]
`NumericalEquality` is probably better, constant feels like it comes with extra baggage. `DistanceEquality` may work, but might imply more than you want.

**Comment by robb** [comment]
:bow:

**Pull request merged**
