### PR TITLE
Make iOS 7 compatible

### PR DESCRIPTION
**Pull request by hboon**

### CODE REVIEW

**Comment by orta** [comment]
Any chance you can rebase this? I'd like to see if it greens. ( Given that the library supports macOS )

**Comment by hboon** [comment]
There you go.

**Comment by orta** [comment]
Yeah, that's what I figured, any chance you can make this happen for iOS targets only? And if that works, I'm happy to have the podspec's iOS version go down to iOS 7 👍

**Comment by hboon** [comment]
Sorry, had to push a second time to use spaces instead of tabs. (Danger anyone? :P)

**Comment by orta** [comment]
Ace 👍

**Comment by orta** [comment]
hah, yeah - would be nice

**Pull request merged**
