### PR TITLE
Fix Xcode 7.3 warning

### PR DESCRIPTION
**Pull request by sebastianvarela**

### CODE REVIEW

**Comment by dcharbonnier** [comment]
@sebastianvarela the build fail ;-)

**Comment by robb** [comment]
Thanks for the pull request! 💖 

Is there any way to get this build on travis?

**Comment by jpsim** [comment]
> Is there any way to get this build on travis?

Sure! Just set the Xcode 7.3 image in `.travis.yml`: `osx_image: xcode7.3`

**Comment by robb** [comment]
Closed in #208, thanks!

**Pull request closed without merging**
